import DrawComponents from "@/components/DrawComponents";
import DrawResult from "@/components/DrawResult";
import styles from "@/styles/Home.module.css";
import { Inter } from "next/font/google";
import Head from "next/head";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [drawOptions, setDrawOptions] = useState("");

  return (
    <>
      <Head>
        <title>Çekiliş</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <DrawComponents setDrawOptions={setDrawOptions} />
        <DrawResult drawOptions={drawOptions} />
      </main>
    </>
  );
}
